### ISSUE TITLE
QuickPlay2.0 forces default Minecraft resource pack

### ISSUE THREAD

**Issue by Snuggle** [bugfroggy/Quickplay2.0#6] opened 2018-02-24 08:24 UTC
**Bug Name:** QuickPlay2.0 forces default Minecraft resource pack
**Issue ID:** #6
**Version Number:** Quickplay2.0 (Beta)
**Minecraft Version Number:** 1.8.9 w/ Forge (FML)
**Forge Version Number:** 11.15.1.2318-1.8.9
**Reported By:** Snuggle
**Reported On:** 2018-02-24
**Environment:** Solus_x86-64 (Linux Distro)
**Neofetch:**
![image](https://user-images.githubusercontent.com/26250962/36626514-089ad558-192c-11e8-8036-f96e80fd912b.png)

**Description:**
Minecraft fails to stitch textures after QuickPlay appears to register its own. This causes it to remove all resource packs and use default.

Only appears to occur during Forge preInit/init/postInit stage. Once Minecraft is open, you can load a resource pack without issues. Resource pack will not persist after restarting Minecraft, however.

Might be due to using a higher resolution resource pack. (x128/x256)

**Stacktrace:**
```[08:09:57] [pool-3-thread-6/INFO]: Caught error stitching, removing all assigned resourcepacks
net.minecraft.util.ReportedException: Registering texture
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:89) ~[bmj.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(TextureManager.java:144) ~[bmj.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:130) ~[bnn.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:111) ~[bnn.class:?]
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:732) ~[ave.class:?]
	at co.bugg.quickplay.config.AssetFactory.loadIcons(AssetFactory.java:89) ~[AssetFactory.class:?]
	at co.bugg.quickplay.http.response.ResponseAction.lambda$run$2(ResponseAction.java:91) ~[ResponseAction.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_172-solus]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_172-solus]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172-solus]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172-solus]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172-solus]
Caused by: java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.GL11.glDeleteTextures(GL11.java:732) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at net.minecraft.client.renderer.GlStateManager.func_179150_h(SourceFile:337) ~[bfl.class:?]
	at net.minecraft.client.renderer.texture.TextureUtil.func_147942_a(TextureUtil.java:38) ~[bml.class:?]
	at net.minecraft.client.renderer.texture.AbstractTexture.func_147631_c(SourceFile:54) ~[bly.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:24) ~[bme.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:67) ~[bmj.class:?]
	... 11 more
```

**Full crashlog:**
https://pastebin.com/j1cNd7jM

**Steps To Reproduce:**
1) Use Forge version above.
2) Have Liteloader-1.8.9 SNAPSHOT installed. (Probably unrelated)
3) Open Minecraft
4) Load a resource pack.
(Tested with Sphax PureBDCraft | x64, x128 & x256) http://bdcraft.net/purebdcraft-minecraft
5) Restart Minecraft. (It works fine until you restart Minecraft and Forge attempts to initialize)
6) Resource pack won't be loaded as texture stitching will fail.

_This bug can be reproduced with no other modifications present. No Optifine etc._

**Comment by robere2** [comment] 2018-02-25 00:31
This issue is caused by refreshing resources when icons are loaded or when the game starts.
Temporarily fixed in 629847728764b8ac9d56d7e22b0d69d2e879a2fb by not refreshing resources at all.
This might cause an issue with icons having a missing texture during first install/when a new game is added.
1.12 clients might also have a missing texture issue once this is ported to 1.12, I'm not sure what the underlying cause is.

**Comment by Snuggle** [comment] 2018-03-04 21:17
Perhaps you could make it only refresh resources on `1.12+` clients?

**Comment by robere2** [comment] 2018-03-05 05:35
Once I get to that point I'll look into it further. I did some digging for a new feature coming out in the next version and it seems like I found a way to refresh specific resources without affecting the game or other resources.

**Closed as completed** 2018-03-13 21:23 UTC
Labels: Type: Bug, Priority: MED
