### ISSUE TITLE
/quickplay delivery attempts an invalid command server-side.

### ISSUE THREAD

**Issue by Snuggle** [bugfroggy/Quickplay2.0#1] opened 2018-02-24 06:50 UTC
Doing `/quickplay delivery` or `/qp delivery` on the Hypixel Network results in an server-side error. You may want to check what command it's trying to run.

![image](https://user-images.githubusercontent.com/26250962/36626671-d619f246-192e-11e8-8b4b-e496152bcb94.png)

**Comment by robere2** [comment] 2018-02-24 07:25
This seems like a Hypixel bug potentially. Talked with you in Slack. Gonna look into this further.

**Comment by robere2** [comment] 2018-02-25 01:40
Closing this since I'm unable to reproduce. Please let me know if this happens again with more information.

**Closed as completed by robere2** 2018-02-25 01:40 UTC
Labels: Type: Bug, Cannot reproduce
